### PR TITLE
Proposal: Allow breakpoint to take option::run option type

### PR DESCRIPTION
**Pull request by aaronlehmann**
@coryb raised the point that having a separate option type for breakpoints
inhibits code reuse, since functions providing option::run values can't
be reused for breakpoints. This PR explores an alternative where
breakpoint uses the option::run type instead of defining its own option
type.

There is definitely some language ugliness in making breakpoint a
special case here, but the tradeoff is that it allows for a better user
experience when otherwise functions providing option::run values
wouldn't be usable for a `breakpoint`. This has come up internally in my
prototyping and required some template abuse to use the same mounts,
cwd, security option, etc. for a breakpoint as we're using for runs.

Opened against https://github.com/openllb/hlb/pull/253

@hinshun - any thoughts?

### CODE REVIEW

**Comment by aaronlehmann** [comment]
cc @retrohacker (thanks for the idea!)

**Comment by coryb** [comment]
If we go this route we probably need to update the breakpoint description in the builtin.hlb to make it clear that it accepts `option::run`.   My other idea which maybe also be bad was to add `option::run breakpoint` so something like this:
```
fs foo() {
  image "alpine"
  run "apk add -U curl" with option {
    dir "/root"
    env "foo" "bar"
    mount scratch "/some/path" with option {
      cache "some/path-mount" "private"
    }
    breakpoint
  }
}
```

The concern there is that it is not clear we want a shell or that `apk add -U curl` should not be run in that `breakpoint`.  Perhaps `option::run breakpoint(variadic string command)` would work?
```
fs foo() {
  image "alpine"
  run "apk add -U curl" with option {
    dir "/root"
    env "foo" "bar"
    mount scratch "/some/path" with option {
      cache "some/path-mount" "private"
    }
    breakpoint "/bin/bash" "-l"
  }
}
```
That feels a bit more intuitive to me in that we want to execute bash via the debugger.   Not sure what the zero-argument `breakpoint` would be, maybe `/bin/sh` or just run the args to `run` with a tty attached?

**Comment by hinshun** [comment]
I didn't know `breakpoint` now accepted arguments cause previously I saw it as a keyword rather than a builtin func. The `option::run breakpoint` seems like a better idea, I'm not a fan of breakpoint taking `option::run`.

Zero-argument running args to `run` makes sense to me. Since it's a `breakpoint` though, does that mean after exiting the from exec you go into the debugger? Or does the solve just continue?

**Comment by aaronlehmann** [comment]
> Since it's a breakpoint though, does that mean after exiting the from exec you go into the debugger? 

`breakpoint` doesn't do anything unless you're running in the debugger. If you are in the debugger, you'll get a debugger prompt after the exec finishes.

**Comment by hinshun** [comment]
So if you are not in the debugger, does that mean `option::run breakpoint` doesn't trigger?

**Comment by aaronlehmann** [comment]
> So if you are not in the debugger, does that mean `option::run` breakpoint doesn't trigger?

Yes, that's what I think is the right behavior. I wouldn't expect a breakpoint to do anything outside of a debugger.

(Note that "debugger" doesn't necessarily mean the stock debugger in `debug.go` - it can be any callback passed into HLB using `WithDebugger` which handles breakpoints).

> The `option::run` breakpoint seems like a better idea, I'm not a fan of breakpoint taking `option::run`.

I understand the perspective and ultimately I think I'm fine going this way, but I feel it has some downsides.

- If I want a simple breakpoint, I can add the line `breakpoint` to my HLB code.
- ...but if I want any mounts, I have to change it to a `run ... with option { breakpoint }` instead? (and it seems weird that I'd use a run for this in the first place).
- In @coryb's example of `run "apk add ..."`, does adding a breakpoint break before or after running apk? Or does it replace the apk command entirely with the interactive shell? None of these options seem particularly intuitive. What if I want a breakpoint with mounts, but I don't want to run anything except the shell. Do I need `run "true" with option { breakpoint "/bin/sh" }`? That seems less than optimal.

Using `run` feels like an ugly workaround for options not being reusable between different types of builtins. Maybe it's the best we can do for now, but I feel like I should point out the concerns.

**Comment by hinshun** [comment]
From BuildKit's perspective, mounts only exist on execops aka `run`. If you're going to treat breakpoint as a `run`, I think it makes sense that it's a part of `run`. The way I reason about it is that most breakpoints are between statements, whereas a breakpoint with mounts is during the `run` operation.

> What if I want a breakpoint with mounts, but I don't want to run anything except the shell.

I think it would be `run "/bin/sh" with option { mount ...; breakpoint }`

**Comment by aaronlehmann** [comment]
> > What if I want a breakpoint with mounts, but I don't want to run anything except the shell.

> I think it would be `run "/bin/sh" with option { mount ...; breakpoint }`

Okay, so in `run "apk add -U curl" with option { mount ...; breakpoint "/bin/sh" }`, should the `/bin/sh` override the `apk add`? Or should we not even support that syntax, and the author of the file should have to change the `run` command to a shell if they want a shell?

**Comment by hinshun** [comment]
So with the gateway exec, we can actually control if we should exec before run is executed, or after its executed. Maybe by default it's before, so in essence the `/bin/sh` overrides, but maybe the `breakpoint` has an option to exec after `apk add -U curl` has executed.

**Comment by aaronlehmann** [comment]
> So with the gateway exec, we can actually control if we should exec before run is executed, or after its executed. Maybe by default it's before, so in essence the `/bin/sh` overrides, but maybe the `breakpoint` has an option to exec after `apk add -U curl` has executed.

But if you do `run "/bin/sh" with option { mount ...; breakpoint }`, you are implicitly using the `/bin/sh` as the command to run in the gateway exec (and not running it in an `ExecOp`, I assume), so I don't think the before/after distinction even comes up.

This is part of why I find "breakpoint as part of run" confusing. The semantics around what actually gets run outside the interactive session (or not) don't seem very clear. I feel we should either design this so that a breakpoint always replaces `ExecOp` with an interactive gateway exec, or always runs the gateway exec before/after it (ideally just pick one or the other).

**Comment by coryb** [comment]
I kind of feel like we should have `option::run breakpoint(string command, variadic string args)`, so we require at least one argument and that argument would be what we execute:
```
run "apk add -U curl" with option {
  breakpoint "/bin/bash"
}
```
For the use case of "I want a shell without a run statement" I am not sure that has any practical use. I expect the gateway-exec to be used primarily as a way to debug environments for run statements (ie env, mounts,  etc), that said I think it can still be accomplished with:
```
run "true" with option {
  breakpoint "/bin/bash"
}
```
or even:
```
run "" with option {
  breakpoint "/bin/bash"
}
```
Both of those are ugly, but I don't expect them to be used in practice.  What would be useful is the `breakpoint` instruction we already have:
```
fs default() {
  image "alpine"
  breakpoint
}
```
That seems useful, in that I run `hlb run --debug`, type `c` to continue which will stop at the `breakpoint`, then type "exec /bin/bash" to get a container, no run statement is necessary there.  The workflow with `option::run breakpoint` I think would be:
```
fs default() {
 image "alpine"
 run "whatever" with option {
   mount somefs "/stuff"
   breakpoint "/bin/bash"
  }
}
```
where we run `hlb run --debug`,  type `c` to continue and it will break the breakpoint and automatically exec to /bin/bash.

**Comment by coryb** [comment]
for the before/after I think the default should be "before", and eventually we can add some `option::breakpoint` like @hinshun mentioned. Something like `breakpoint "/bin/bash" with exec("after")` or `breakpoint "/bin/bash with exec("onError")` to handle the "only get me a shell after the command has run if it returns an error" case?

**Comment by aaronlehmann** [comment]
@coryb: I think your proposal is very reasonable. One minor quibble:

> where we run hlb run --debug, type c to continue and it will break the breakpoint and automatically exec to /bin/bash.

If the behavior will be to automatically exec the interactive shell rather than give a debugger prompt, I'm wondering if `breakpoint` is the right name for the run option. Maybe something like `interactiveShell`, `debugCommand`, or `preRunShell` would be a better name. This would also help distinguish the option from the actual `breakpoint` statement which doesn't have a mandatory argument and doesn't necessarily kick off a gateway exec.

Or we could say that the run option does break into the debugger, and doesn't do a gateway exec until/unless the user types `exec` (programs which embed HLB can override this behavior, of course). Then I think the name `breakpoint` would make sense.

**Comment by coryb** [comment]
yeah, I am fine with the stock debugger requiring `exec` to enter the container using the specified options from hlb file.  As long as we can accomplish the "automatically go into exec" via a custom `WithDebugger` implementation.

**Pull request closed without merging**
